# vim: ft=dosini
#
# aerc Nyx styleset
# set styleset-name=nyx-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#ebebeb
border.bg=#faf9f5

title.fg=#c8c7c4
title.bg=#0A89FF
title.bold=true

header.fg=#ca0043
#header.bg=#faf9f5
header.bold=true

tab.fg=#ebebeb
tab.bg=#faf9f6
tab.selected.fg=#c8c7c4
tab.selected.bg=#0A89FF

statusline_default.fg=#101010
statusline_default.bg=#faf9f6
statusline_error.fg=#701516
statusline_success.fg=#407f00

*error.bold=true
*error.fg=#701516
*warning.fg=#b07700
*success.fg=#407f00

dirlist_*.bg=#faf9f5
dirlist_*.fg=#101010
dirlist_*.selected.bg=#aeaeab
dirlist_*.selected.fg=#101010

msglist_*.bg=#faf9f5
msglist_*.fg=#101010
msglist_*.selected.bg=#aeaeab
#msglist_*.selected.fg=#101010
msglist_unread.bold=true
msglist_unread.fg=#0A89FF
msglist_marked.fg=#FF7038
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#ebebeb
msglist_pill.bg=#ebebeb
msglist_pill.reverse=false

part_*.fg=#101010
part_*.bg=#faf9f6
part_*.selected.fg=#101010
part_*.selected.bg=#ebebeb

completion_default.bg=#faf9f6
completion_default.fg=#101010
completion_default.selected.bg=#ebebeb
completion_default.selected.fg=#101010
completion_gutter.bg=#ebebeb
completion_pill.bg=#ebebeb
completion_pill.reverse=false

spinner.bg=#faf9f5
spinner.fg=#101010

selector_focused.bold=false
selector_focused.bg=#aeaeab
selector_focused.fg=#101010
selector_chooser.bold=false
selector_chooser.bg=#aeaeab
selector_chooser.fg=#101010
default.selected.bold=false
default.selected.fg=#101010
default.selected.bg=#aeaeab

[viewer]
url.underline=true
url.fg=#101010
header.fg=#f2a4db
signature.fg=#f2a4db
diff_add.fg=#c3e4ca
diff_del.fg=#d8c0bd
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#b07700
quote_2.fg=#407f00
quote_3.fg=#5abfb5
quote_3.dim=true
quote_4.fg=#0A89FF
quote_4.dim=true
quote_x.fg=#969ba5
quote_x.dim=true

