# vim: ft=dosini
#
# aerc Nyx styleset
# set styleset-name=nyx-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#272727
border.bg=#101010

title.fg=#0d0d0d
title.bg=#458ee6
title.bold=true

header.fg=#701516
#header.bg=#101010
header.bold=true

tab.fg=#272727
tab.bg=#0c0c0c
tab.selected.fg=#0d0d0d
tab.selected.bg=#458ee6

statusline_default.fg=#b0b0b0
statusline_default.bg=#0c0c0c
statusline_error.fg=#ff9999
statusline_success.fg=#86cd82

*error.bold=true
*error.fg=#ff9999
*warning.fg=#d9ba73
*success.fg=#86cd82

dirlist_*.bg=#101010
dirlist_*.fg=#b0b0b0
dirlist_*.selected.bg=#393939
dirlist_*.selected.fg=#b0b0b0

msglist_*.bg=#101010
msglist_*.fg=#b0b0b0
msglist_*.selected.bg=#393939
#msglist_*.selected.fg=#b0b0b0
msglist_unread.bold=true
msglist_unread.fg=#458ee6
msglist_marked.fg=#FF7038
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#272727
msglist_pill.bg=#272727
msglist_pill.reverse=false

part_*.fg=#b0b0b0
part_*.bg=#0c0c0c
part_*.selected.fg=#b0b0b0
part_*.selected.bg=#272727

completion_default.bg=#0c0c0c
completion_default.fg=#b0b0b0
completion_default.selected.bg=#272727
completion_default.selected.fg=#b0b0b0
completion_gutter.bg=#272727
completion_pill.bg=#272727
completion_pill.reverse=false

spinner.bg=#101010
spinner.fg=#b0b0b0

selector_focused.bold=false
selector_focused.bg=#393939
selector_focused.fg=#b0b0b0
selector_chooser.bold=false
selector_chooser.bg=#393939
selector_chooser.fg=#b0b0b0
default.selected.bold=false
default.selected.fg=#b0b0b0
default.selected.bg=#393939

[viewer]
url.underline=true
url.fg=#b0b0b0
header.fg=#f2a4db
signature.fg=#f2a4db
diff_add.fg=#113512
diff_del.fg=#4c3232
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#d9ba73
quote_2.fg=#86cd82
quote_3.fg=#5abfb5
quote_3.dim=true
quote_4.fg=#458ee6
quote_4.dim=true
quote_x.fg=#50585d
quote_x.dim=true

