# -----------------------------------------------------------------------------
# Nyx Alacritty Colors
# Theme: Nyx Darker
# Upstream: https://github.com/serhez/nyx.nvim/raw/main/extras/alacritty/nyx_darker.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#101010'
foreground = '#b0b0b0'

# Normal colors
[colors.normal]
black = '#0d0d0d'
red = '#ff7676'
green = '#86cd82'
yellow = '#FF7038'
blue = '#458ee6'
magenta = '#f2a4db'
cyan = '#5abfb5'
white = '#777777'

# Bright colors
[colors.bright]
black = '#272727'
red = '#701516'
green = '#5abfb5'
yellow = '#d9ba73'
blue = '#8ebeec'
magenta = '#f2a4db'
cyan = '#5abfb5'
white = '#b0b0b0'
