[[themes]]
name = "Nyx Light"
[themes.palette]
background = "#faf9f6"
foreground = "#3d3d3d"
black = "#ebebeb"
red = "#ca0043"
green = "#407f00"
yellow = "#b07700"
blue = "#0A89FF"
magenta = "#f2a4db"
cyan = "#5abfb5"
white = "#3d3d3d"
bright_black = "#faf9f5"
bright_red = "#701516"
bright_green = "#407f00"
bright_yellow = "#FF7038"
bright_blue = "#0253be"
bright_magenta = "#f2a4db"
bright_cyan = "#0A89FF"
bright_white = "#101010"
