[[themes]]
name = "Nyx Darker"
[themes.palette]
background = "#0c0c0c"
foreground = "#777777"
black = "#272727"
red = "#ff7676"
green = "#86cd82"
yellow = "#d9ba73"
blue = "#458ee6"
magenta = "#f2a4db"
cyan = "#5abfb5"
white = "#777777"
bright_black = "#101010"
bright_red = "#701516"
bright_green = "#86cd82"
bright_yellow = "#FF7038"
bright_blue = "#8ebeec"
bright_magenta = "#f2a4db"
bright_cyan = "#8ebeec"
bright_white = "#b0b0b0"
