# vim:ft=kitty

## name: Nyx Light
## license: MIT
## authors: Folke Lemaitre & Sergio Hernandez
## upstream: https://github.com/serhez/nyx.nvim/raw/main/extras/kitty/nyx_light.conf


background #faf9f5
foreground #101010
selection_background #aeaeab
selection_foreground #101010
url_color #407f00
cursor #101010
cursor_text_color #faf9f5

# Tabs
active_tab_background #0A89FF
active_tab_foreground #faf9f6
inactive_tab_background #ebebeb
inactive_tab_foreground #3d3d3d
#tab_bar_background #c8c7c4

# Windows
active_border_color #0A89FF
inactive_border_color #ebebeb

# normal
color0 #c8c7c4
color1 #ca0043
color2 #407f00
color3 #FF7038
color4 #0253be
color5 #f2a4db
color6 #0A89FF
color7 #3d3d3d

# bright
color8  #ebebeb
color9  #701516
color10 #5abfb5
color11 #b07700
color12 #5abfb5
color13 #f2a4db
color14 #5abfb5
color15 #101010

# extended colors
color16 #FF7038
color17 #701516
